### ISSUE TITLE
Error in Console for JupyterLab notebook. TypeError: Cannot read property 'context' of null

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow-jupyterlab-plugin#58]
**Description**

Error in Console for JupyterLab notebook. TypeError: Cannot read property 'context' of null

**Steps to Reproduce:**

1. Open JupyterLab Notebook.
2. Open Console in DevTools.
3. Switch between tabs on sidebar (folder, cloud, palette, tabs) in JupyterLab Notebook.
4. Notice that the Error appears in Console.

**Actual result**

The error is present: `TypeError: Cannot read property 'context' of null`.

**Expected result**

There is no errors in Console.

**Attachments**

https://user-images.githubusercontent.com/49116723/118259134-7502cf80-b4b9-11eb-9cc8-33655c8dbc02.mov

**Comment by alinaignatiuk** [comment]
Check whether this is UI bug or not
