### ISSUE TITLE
Cannot remove any entity: `'_xsrf' argument missing from POST`

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow-jupyterlab-plugin#59]
**Description**
when you try to delete an entity the window pops up with message: `'_xsrf' argument missing from POST`.

**Steps to Reproduce**
1. Go to 'ODAHU' JupyterLab plugin.
1. Click on any entity which should be removable.
1. Click on `Remove` button.
1. Look at the message which pops up.

**Actual result**
The entities can be removed

**Expected result**
The entities cannot be removed through the JupyterLab plugin.

**Attachments**

https://user-images.githubusercontent.com/49116723/119003499-71c68280-b996-11eb-9e46-e6fb03467b01.mp4

**Comment by alinaignatiuk** [comment]
Cannot reproduce

**Comment by BPylypenko** [comment]
As I could not reproduce it during regression testing of 1.5.0 release, I am closing the issue.
