### ISSUE TITLE
Refresh logs if user restart a training

### ISSUE THREAD

**Issue by mashironshiina** [odahu/odahu-flow-jupyterlab-plugin#7]
Test case:
* Starts a training
* Opens the view of training logs
* Wait until training finished
* Restart the training

ER:
The training log view streams new logs.

AR:
The view contains logs from old training.
User must reopen the view to see logs from the restarted training.

**Comment by vlad-tokarev** [comment]
we should not allow restart training, ID of training and packaging must be generated and unique
